import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Embedding, Bidirectional
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Sample dataset (questions and corresponding answers)
questions = [
    "What is a linked list?",
    "Explain the concept of a stack.",
    "What is the purpose of a heap data structure?",
    "How do you perform insertion in a binary search tree?",
    "What is a breadth-first search?",
    "What is the time complexity of quicksort?",
    "How does binary search work?",
    "What are the types of sorting algorithms?",
    "Describe the concept of recursion.",
    "What is the difference between a stack and a queue?",
    "How do you implement a priority queue?",
    "Explain the concept of dynamic programming.",
    "What is the purpose of hashing?",
    "What is a tree traversal algorithm?",
    "What is the difference between depth-first search and breadth-first search?",
    "What are the advantages of using a linked list over an array?",
    "How do you reverse a linked list?",
    "What is an AVL tree?",
    "What is an adjacency matrix?",
    "How do you detect a cycle in a graph?",
    "Explain the concept of a directed graph.",
    "What is the time complexity of linear search?",
    "What is the purpose of graph traversal algorithms?",
    "Describe the concept of a doubly linked list.",
    "What is a topological sort?",
    "How do you implement a hash table?",
    "What is a suffix array?",
    "What is the use of a trie data structure?",
    "What is the difference between a graph and a tree?",
    "Explain the concept of a balanced binary tree.",
    "What are the applications of dynamic programming?",
    "What is a min-heap and a max-heap?",
    "Describe the concept of a red-black tree.",
    "How do you perform a preorder traversal of a binary tree?",
    "What is the time complexity of bubble sort?",
    "What is a graph cycle?",
    "Explain the concept of backtracking.",
    "What is the difference between DFS and BFS?",
    "What is an undirected graph?",
    "How do you perform an inorder traversal of a binary tree?",
    "What is a circular linked list?",
    "Explain the concept of a priority queue.",
    "What is a Fibonacci heap?",
    "How do you perform a postorder traversal of a binary tree?",
    "What is the purpose of Dijkstra's algorithm?",
    "What is a spanning tree?",
    "What is a trie?",
    "Explain the concept of a minimum spanning tree.",
    "What is a k-d tree?",
    "What is the use of Floyd-Warshall algorithm?",
    "How do you insert and delete elements in a heap?",
    "What is the time complexity of merge sort?",
    "What is the use of Kruskal's algorithm?",
    "What is a binary search tree?",
    "Explain the concept of a hash function.",
    "What is the time complexity of selection sort?",
    "What is a binary heap?",
    "What is the purpose of Bellman-Ford algorithm?",
    "What is a graph edge?",
    "Explain the concept of a hash collision.",
    "What is the time complexity of insertion sort?",
    "What is a graph vertex?",
    "What is the use of Prim's algorithm?",
    "What is a graph path?",
    "Explain the concept of a heapify operation.",
    "What is a Fibonacci sequence?",
    "What is a graph degree?",
    "What is the use of Floyd's algorithm?",
    "What is a B-tree?",
    "Explain the concept of a minimum heap.",
    "What is a graph adjacency list?",
    "What is the use of Johnson's algorithm?",
    "What is a graph diameter?",
    "Explain the concept of a maximum heap.",
    "What is a graph connected component?",
    "What is the use of Edmonds-Karp algorithm?",
    "What is a graph cycle detection?",
    "Explain the concept of a minimum cut in a graph.",
    "What is a graph bipartite checking?",
    "What is a graph Eulerian path?",
    "Explain the concept of a Hamiltonian path in a graph.",
    "What is a graph chromatic number?",
    "What is the use of Ford-Fulkerson algorithm?",
    "What is a graph topological ordering?",
    "Explain the concept of a minimum spanning tree in a weighted graph.",
    "What is a graph articulation point?",
    "What is the use of Kosaraju's algorithm?",
    "What is a graph transitive closure?",
    "Explain the concept of a maximum flow in a network graph.",
    "What is a graph planarity checking?",
    "What is a graph strongly connected component?",
    "What is the use of Tarjan's algorithm?",
    "Explain the concept of a critical path in a graph.",
    "What is a graph edge coloring?",
    "What is the use of Hungarian algorithm?"
]

answers = [
    "A linked list is a linear data structure consisting of a sequence of elements, each connected to the next by a pointer or reference.",
    "A stack is a linear data structure that follows the Last In, First Out (LIFO) principle. Elements are inserted and removed from the top of the stack.",
    "A heap is a specialized tree-based data structure that satisfies the heap property. It is commonly used to implement priority queues and heap sort algorithms, where the highest (or lowest) priority element is always at the root.",
    "To perform insertion in a binary search tree, you compare the value of the new node with the value of the current node. If the value is less than the current node, you recursively insert it into the left subtree; if it is greater, you insert it into the right subtree.",
    "Breadth-first search (BFS) is a graph traversal algorithm that explores all the neighbor nodes at the present depth before moving on to the nodes at the next depth level.",
    "The average and best-case time complexity of quicksort is O(n log n), while the worst-case time complexity is O(n^2). However, quicksort is widely used due to its average-case efficiency.",
    "Binary search is an efficient algorithm for finding a target value within a sorted array. It repeatedly divides the search interval in half until the target value is found or the interval is empty.",
    "Sorting algorithms can be categorized into various types, including bubble sort, selection sort, insertion sort, merge sort, quicksort, heap sort, and radix sort.",
    "Recursion is a programming technique in which a function calls itself to solve smaller instances of the same problem. It is commonly used in algorithms such as tree traversal, sorting, and searching.",
    "A stack and a queue are both linear data structures, but they differ in the order in which elements are inserted and removed. A stack follows the Last In, First Out (LIFO) principle, while a queue follows the First In, First Out (FIFO) principle.",
    "A priority queue is a data structure that stores elements along with their associated priorities and supports operations such as insertion and deletion of the element with the highest (or lowest) priority.",
    "Dynamic programming is a method used to solve problems by breaking them down into simpler subproblems and solving each subproblem only once, storing the solutions to subproblems in a table to avoid redundant computations.",
    "Hashing is a technique used to map data of arbitrary size to fixed-size values, typically integers, with the purpose of speeding up data retrieval and storage.",
    "Tree traversal algorithms are used to visit all the nodes in a tree data structure in a systematic manner. Common traversal methods include inorder, preorder, and postorder traversals.",
    "Depth-first search (DFS) and breadth-first search (BFS) are two common algorithms for traversing or searching tree or graph data structures. DFS explores as far as possible along each branch before backtracking, while BFS explores all neighbor nodes at the present depth before moving on to the next depth level.",
    "Linked lists have several advantages over arrays, including dynamic size, ease of insertion and deletion, and efficient memory utilization. Unlike arrays, linked lists do not require contiguous memory allocation, making them suitable for scenarios where memory is fragmented or unpredictable.",
    "To reverse a linked list, you can traverse the list while keeping track of the previous, current, and next nodes. At each step, update the next pointer of the current node to point to the previous node, and then move the pointers one step forward.",
    "An AVL tree, also known as a self-balancing binary search tree, is a binary search tree where the height difference between the left and right subtrees of any node is at most one. AVL trees maintain balance during insertion and deletion operations to ensure efficient searching.",
    "An adjacency matrix is a square matrix used to represent a graph, where the elements of the matrix indicate whether pairs of vertices are adjacent or not. A value of 1 typically indicates an edge between two vertices, while 0 indicates no edge.",
    "To detect a cycle in a graph, you can use algorithms such as depth-first search (DFS) or breadth-first search (BFS). During traversal, if you encounter a vertex that is already visited and not the parent of the current vertex, then there is a cycle in the graph.",
    "A directed graph, also known as a digraph, is a graph in which edges have a direction associated with them. This means that the connection between vertices is one-way, unlike undirected graphs where edges have no direction.",
    "The time complexity of linear search is O(n), where n is the number of elements in the array. Linear search sequentially checks each element in the array until the target element is found or the end of the array is reached.",
    "Graph traversal algorithms are used to visit all the vertices in a graph or a portion of the graph. They are essential for solving various graph problems, such as finding connected components, topological sorting, and detecting cycles.",
    "A doubly linked list is a linked list where each node contains two pointers: one pointing to the next node in the sequence and another pointing to the previous node. This allows traversal of the list in both forward and backward directions.",
    "Topological sort is an algorithm used to linearly order the vertices of a directed acyclic graph (DAG) in such a way that for every directed edge uv from vertex u to vertex v, u comes before v in the ordering.",
    "A hash table, also known as a hash map, is a data structure that stores key-value pairs, where each key is hashed to a unique index in an array. This allows for fast insertion, deletion, and retrieval of elements based on their keys.",
    "A suffix array is an array containing all the suffixes of a given string, sorted in lexicographical order. Suffix arrays are useful in various string processing tasks, such as pattern matching and substring search.",
    "A trie, also known as a prefix tree, is a tree data structure used to efficiently store and retrieve strings. Each node of the trie represents a common prefix of the strings stored in the trie.",
    "A graph is a collection of vertices (nodes) and edges (connections) between pairs of vertices. Unlike trees, graphs may contain cycles and may not have a root node.",
    "A balanced binary tree is a binary tree in which the heights of the two child subtrees of any node differ by at most one. Balanced trees ensure that the depth of the tree remains logarithmic, leading to efficient search, insertion, and deletion operations.",
    "Dynamic programming is used to solve problems by breaking them down into simpler subproblems and solving each subproblem only once, storing the solutions to subproblems in a table to avoid redundant computations. It is commonly used in optimization problems and problems with overlapping subproblems.",
    "A min-heap is a binary tree-based data structure where the parent nodes are smaller than or equal to their child nodes. The root node contains the smallest element in the heap, and the heap property is maintained such that for any node i, the value of the parent is less than or equal to the value of node i.",
    "A red-black tree is a self-balancing binary search tree where each node contains an extra bit representing the color of the node (red or black). The tree satisfies several properties that ensure balance during insertion and deletion operations, leading to efficient searching.",
    "Preorder traversal is a tree traversal algorithm that visits the root node first, followed by the left subtree, and then the right subtree. In other words, it recursively visits the nodes in the order root, left, right.",
    "The time complexity of bubble sort is O(n^2), where n is the number of elements in the array. Bubble sort repeatedly compares adjacent elements and swaps them if they are in the wrong order until the entire array is sorted.",
    "A graph cycle, also known as a cycle or loop, is a sequence of vertices in a graph that forms a path such that the starting and ending vertices are the same, and the path contains at least one edge.",
    "Backtracking is a problem-solving technique used to find all (or some) solutions to a computational problem. It incrementally builds a solution and abandons it if it determines that the solution cannot be completed further.",
    "Depth-first search (DFS) and breadth-first search (BFS) are two common algorithms for traversing or searching tree or graph data structures. DFS explores as far as possible along each branch before backtracking, while BFS explores all neighbor nodes at the present depth before moving on to the next depth level.",
    "An undirected graph is a graph in which edges have no direction associated with them. This means that the connection between vertices is bidirectional, allowing traversal in both directions along the edges.",
    "Inorder traversal is a tree traversal algorithm that visits the left subtree first, followed by the root node, and then the right subtree. In other words, it recursively visits the nodes in the order left, root, right.",
    "A circular linked list is a variation of a linked list where the last node points back to the first node, forming a circular structure. This allows traversal of the list starting from any node and looping back to the beginning.",
    "A priority queue is a data structure that stores elements with associated priorities and supports operations such as insertion and deletion of the element with the highest (or lowest) priority.",
    "A Fibonacci heap is a type of heap data structure that supports the mergeable heap operations efficiently, including insert, find minimum, extract minimum, decrease key, and merge.",
    "Postorder traversal is a tree traversal algorithm that visits the left subtree first, followed by the right subtree, and then the root node. In other words, it recursively visits the nodes in the order left, right, root.",
    "Dijkstra's algorithm is a shortest path algorithm used to find the shortest path between nodes in a weighted graph. It works by repeatedly selecting the node with the smallest distance from a set of unvisited nodes.",
    "A spanning tree of a graph is a subgraph that contains all the vertices of the graph and is a tree (i.e., it is connected and acyclic). A minimum spanning tree is a spanning tree with the minimum possible total edge weight.",
    "A trie, also known as a prefix tree, is a tree data structure used to efficiently store and retrieve strings. Each node of the trie represents a common prefix of the strings stored in the trie.",
    "A minimum spanning tree of a weighted graph is a spanning tree with the minimum possible total edge weight. It connects all the vertices of the graph with the minimum total cost.",
    "A k-d tree, also known as a k-dimensional tree, is a binary tree data structure used for organizing points in a k-dimensional space. It is commonly used in multidimensional search and range query problems.",
    "The Floyd-Warshall algorithm is used to find the shortest paths between all pairs of vertices in a weighted graph. It works by considering all intermediate vertices as possible paths between any two vertices and updating the shortest path accordingly.",
    "Inserting and deleting elements in a heap involve maintaining the heap property, which ensures that the parent nodes are smaller than or equal to their child nodes. Insertion adds a new element to the heap and performs a heapify operation to restore the heap property, while deletion removes the root element and performs a heapify operation to maintain the heap property.",
    "The time complexity of merge sort is O(n log n), where n is the number of elements in the array. Merge sort divides the array into smaller subarrays, recursively sorts them, and then merges the sorted subarrays to produce the final sorted array.",
    "Kruskal's algorithm is a greedy algorithm used to find the minimum spanning tree of a connected, undirected graph. It works by repeatedly selecting the smallest edge that does not form a cycle in the current spanning tree.",
    "A binary search tree (BST) is a binary tree data structure in which each node has at most two child nodes (left and right), and the key value of each node is greater than all keys in its left subtree and less than all keys in its right subtree.",
    "A hash function is a function used to map data of arbitrary size to fixed-size values, typically integers, with the purpose of speeding up data retrieval and storage.",
    "The time complexity of selection sort is O(n^2), where n is the number of elements in the array. Selection sort repeatedly selects the smallest (or largest) element from the unsorted part of the array and swaps it with the first unsorted element.",
    "A binary heap is a binary tree-based data structure where the parent nodes are smaller than or equal to their child nodes. It is commonly used to implement priority queues and heap sort algorithms.",
    "Bellman-Ford algorithm is used to find the shortest paths from a single source vertex to all other vertices in a weighted graph with negative edge weights. It can also detect negative weight cycles in the graph.",
    "An edge in a graph is a connection between two vertices (nodes). It is typically represented as a pair of vertices, indicating that there is a relationship or interaction between them.",
    "A hash collision occurs when two different keys are hashed to the same index in a hash table. This can lead to data being overwritten or stored in incorrect locations, affecting the performance of hash table operations.",
    "The time complexity of insertion sort is O(n^2) in the worst case, where n is the number of elements in the array. Insertion sort iterates through the array and repeatedly inserts each element into its correct position relative to the already sorted elements.",
    "A vertex in a graph is a fundamental unit that represents a point or location. Vertices are connected by edges to form the structure of the graph.",
    "Prim's algorithm is a greedy algorithm used to find the minimum spanning tree of a connected, undirected graph. It works by repeatedly selecting the smallest edge that connects a vertex in the current tree to a vertex outside the tree.",
    "A graph path is a sequence of vertices in a graph where each consecutive pair of vertices is connected by an edge. It represents a route or journey from one vertex to another in the graph.",
    "Heapify is an operation used to maintain the heap property in a binary heap data structure. It ensures that the parent nodes are smaller than or equal to their child nodes by recursively adjusting the position of nodes.",
    "A Fibonacci sequence is a series of numbers in which each number is the sum of the two preceding ones, usually starting with 0 and 1. It is named after Italian mathematician Leonardo of Pisa, also known as Fibonacci.",
    "The degree of a vertex in a graph is the number of edges incident to that vertex. For directed graphs, the degree of a vertex is further divided into the in-degree (number of incoming edges) and out-degree (number of outgoing edges).",
    "Floyd's algorithm, also known as Floyd-Warshall algorithm, is used to find the shortest paths between all pairs of vertices in a weighted graph. It works by considering all intermediate vertices as possible paths between any two vertices and updating the shortest path accordingly.",
    "A B-tree is a balanced tree data structure used for organizing and storing data in a database or file system. It is optimized for systems that read and write large blocks of data, such as databases and file systems.",
    "A minimum heap is a binary tree-based data structure where the parent nodes are smaller than or equal to their child nodes. It is commonly used to implement priority queues and heap sort algorithms.",
    "An adjacency list is a collection of lists used to represent a graph, where each list contains the neighbors of a particular vertex. This representation is efficient for sparse graphs and allows for fast traversal of adjacent vertices.",
    "Johnson's algorithm is used to find the shortest paths between all pairs of vertices in a weighted graph, even if the graph contains negative edge weights or cycles. It works by reweighting the edges of the graph and running Dijkstra's algorithm on each vertex as a source.",
    "The diameter of a graph is the maximum distance between any pair of vertices in the graph. It represents the longest shortest path in the graph and is a measure of its size or connectivity.",
    "A maximum heap is a binary tree-based data structure where the parent nodes are greater than or equal to their child nodes. It is commonly used to implement priority queues and heap sort algorithms.",
    "A connected component in a graph is a subgraph where every pair of vertices is connected by a path. In other words, it is a maximal set of vertices where there is a path between every pair of vertices.",
    "Edmonds-Karp algorithm is an implementation of the Ford-Fulkerson method used to find the maximum flow in a network graph. It works by repeatedly finding augmenting paths and updating the flow along those paths until no more augmenting paths can be found.",
    "Cycle detection in a graph involves identifying whether the graph contains a cycle or not. This can be done using algorithms such as depth-first search (DFS) or breadth-first search (BFS) to traverse the graph and detect back edges.",
    "A minimum cut in a graph is a set of edges whose removal disconnects the graph into two or more components. Finding the minimum cut in a graph is useful in various network flow and connectivity problems.",
    "A bipartite graph is a graph whose vertices can be divided into two disjoint sets such that every edge connects a vertex from one set to a vertex in the other set. Bipartite checking involves determining whether a given graph is bipartite or not.",
    "An Eulerian path in a graph is a path that visits every edge exactly once. An Eulerian circuit is a special case of an Eulerian path where the path forms a cycle, ending at the same vertex where it started.",
    "A Hamiltonian path in a graph is a path that visits every vertex exactly once. A Hamiltonian cycle is a special case of a Hamiltonian path where the path forms a cycle, ending at the same vertex where it started.",
    "The chromatic number of a graph is the minimum number of colors needed to color the vertices of the graph such that no two adjacent vertices have the same color. It represents the minimum number of resources required to perform certain tasks on the graph.",
    "Ford-Fulkerson algorithm is a method used to find the maximum flow in a network graph. It works by repeatedly finding augmenting paths and updating the flow along those paths until no more augmenting paths can be found.",
    "Topological ordering of a directed graph is a linear ordering of its vertices such that for every directed edge uv from vertex u to vertex v, u comes before v in the ordering. It is used in various applications, such as scheduling tasks and resolving dependencies.",
    "An articulation point in a graph is a vertex whose removal would disconnect the graph into two or more components. Identifying articulation points is useful in network analysis and connectivity problems.",
    "Kosaraju's algorithm is used to find the strongly connected components (SCCs) of a directed graph. It works by performing two depth-first searches (DFS) on the graph to identify the SCCs.",
    "The transitive closure of a graph is a new graph that represents the reachability between pairs of vertices in the original graph. It is useful in various graph algorithms, such as reachability analysis and pathfinding.",
    "Maximum flow in a network graph refers to the maximum amount of flow that can be sent from a source vertex to a sink vertex in the network. It is a measure of the capacity of the network and is used in various network optimization problems.",
    "Planarity checking of a graph involves determining whether the graph can be drawn in a plane without any edge crossings. Planarity is an important property in graph theory and has applications in circuit design and map labeling.",
    "A strongly connected component (SCC) in a directed graph is a subgraph where every pair of vertices is reachable from each other. In other words, it is a maximal set of vertices where there is a path between every pair of vertices.",
    "Tarjan's algorithm is used to find the strongly connected components (SCCs) of a directed graph. It works by performing a depth-first search (DFS) on the graph and maintaining a stack of vertices.",
    "A critical path in a graph represents the longest path from the source to the sink in a directed acyclic graph (DAG). It is used in project management to identify the sequence of tasks that must be completed to minimize the project's duration.",
    "A matching problem in a graph involves finding a subset of edges such that no vertex is incident to more than one edge in the subset. Matching problems have applications in various optimization and assignment problems.",
    "Edge coloring of a graph involves assigning colors to the edges of the graph such that no two adjacent edges have the same color. Edge coloring is used in scheduling, map coloring, and resource allocation problems.",
    "The Hungarian algorithm, also known as the Kuhn-Munkres algorithm, is used to solve the assignment problem in combinatorial optimization. It finds the optimal assignment of tasks to resources or agents to minimize the total cost or maximize the total profit."
]

# Tokenize input texts
tokenizer = Tokenizer()
tokenizer.fit_on_texts(questions)
tokenizer.fit_on_texts(answers)

# Convert text to sequences
question_sequences = tokenizer.texts_to_sequences(questions)
answer_sequences = tokenizer.texts_to_sequences(answers)

# Pad sequences to ensure uniform length
max_len = max(max(len(seq) for seq in question_sequences), max(len(seq) for seq in answer_sequences))
question_sequences_padded = pad_sequences(question_sequences, maxlen=max_len)
answer_sequences_padded = pad_sequences(answer_sequences, maxlen=max_len)

# Define LSTM model
model = Sequential([
    Embedding(input_dim=len(tokenizer.word_index)+1, output_dim=100, input_length=max_len),
    Bidirectional(LSTM(128, return_sequences=True)),
    Dense(len(tokenizer.word_index)+1, activation='softmax')
])

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(question_sequences_padded, np.array(answer_sequences_padded), epochs=3000, batch_size=8)
